### ISSUE TITLE
The bookmark code does not works

### ISSUE THREAD

**Issue by arnon001** [WiLuX-Source/Discord-Token-Login#10]

**Comment by WiLuX-Source** [comment]
This might happen in these following cases:
1.You're using a bot token.(This project do not support this.)
2.You wrote your token with "" or ''.(you should write without them.)
3.You have 2FA enabled on your account so it gets reset after using it once.(Disabling 2FA will fix that issue.)


Lemme know If these fixed your problem.

**Comment by WiLuX-Source** [comment]
Closed due to inactivity.
