### ISSUE TITLE
so how does the bookmark method work? 

### ISSUE THREAD

**Issue by Anekkkk** [WiLuX-Source/Discord-Token-Login#11]
how am i suppose to make a bookmark using the bookmark code i generated?

**Comment by Desu403** [comment]
if you don t know something as simple as bookmark why do u even use github? go on google and learn  basic usage of a browser https://support.google.com/a/users/answer/9282721?hl=en
don't waste dev time on something like this, this is not an "issue", this is your  inability  to save a bookmarm.

**Comment by Anekkkk** [comment]
bruh how am is suppose to save this: 
`javascript:function login(token) {setInterval(() => {document.body.appendChild(document.createElement `iframe`).contentWindow.localStorage.token = `"${token}"`}, 50);setTimeout(() => {location.reload();}, 50);}login('MyToken');`
as a bookmark?

**Comment by Anekkkk** [comment]
nvm i got it

**Comment by Anekkkk** [comment]
@de4su also nigga why you trippin like i fucked your mom? 


oh nvm... i think i did fuck dat whore

**Comment by Desu403** [comment]
> @de4su also nigga why you trippin like i fucked your mom?
> 
> oh nvm... i think i did fuck dat whore

ah yes, "nigga" "mom" "whore" "fuck"  you know so many words, but ur still too dumb to make a bookmark, gg kid.

**Comment by WiLuX-Source** [comment]
Calm down guys. JS has no feature to save a string as a bookmark so you have to add a dummy bookmark and change it to the code.

But de4su is right in his first reply searching about bookmarks instead of opening an issue here how to use bookmarks.

I'm closing this issue now. You two have a good day.
