### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Inceptofn** [WiLuX-Source/Discord-Token-Login#12]
I've been using it for nearly a year but it stopped working yesterday. Any idea?

**Comment by WiLuX-Source** [comment]
Can you explain it with more details pls?

**Comment by WiLuX-Source** [comment]
I tested all of the methods right now they are working as they should be.

**Comment by Bertie2006** [comment]
I refresh the discord.com/register but it does not pop up anymore

Verstuurd vanaf mijn iPhone

**Comment by WiLuX-Source** [comment]
what method you use?

**Comment by Beennuked** [comment]
I just want to chime in on this, I noticed this yesterday as well. The script method does not pop up with the account list on the right side anymore. Just started happening yesterday. You get the main login box on the login page, but not the quick-access login box on the right that would appear. To be clear, I reinstalled through tampermonkey and even deleted my cache and cookies to try and it still did not show up. Tested on 2 different computers through chrome on each.

**Comment by Bertie2006** [comment]
I use tampermonkey. And I've also seen someone else have the same issue Judy now 

Verstuurd vanaf mijn iPhone

**Comment by WiLuX-Source** [comment]
Okay I'll check this out in my free time. You can use Bookmark method meanwhile thx for reporting.

**Comment by WiLuX-Source** [comment]
Caused By : "Class name change HTMLElements"

**Comment by Beennuked** [comment]
Awesome! Thank you! Your work is awesome. I will happily test whenever the fix is implemented. I'll be checking back occasionally.

**Comment by Bertie2006** [comment]
I just noticed I made a lot of typos in the conversation, + it said 'verstuurd van mijn iPhone' sorry for that. Let us know when it's fixed 😀

**Comment by WiLuX-Source** [comment]
I fixed the issue. Thanks for reporting again. If you like this project please don't forget to give us a star it helps us a lot. Have good day!
