### ISSUE TITLE
No longer pops up on web browser

### ISSUE THREAD

**Issue by Beennuked** [WiLuX-Source/Discord-Token-Login#13]
Hey there,

I was using this just fine earlier today, but now the web version no longer brings up my account lists anymore on the right side like it normally would. Not sure if discord made a change in the background that may have broken it within the past hour or so. 

![Capture](https://user-images.githubusercontent.com/97627526/168937742-25e1e9da-4fa9-4b06-8502-57f20aef8032.PNG)

**Comment by WiLuX-Source** [comment]
Let me check thanks for reporting.

**Comment by WiLuX-Source** [comment]
> Not sure if discord made a change in the background that may have broken it within the past hour or so.

Yes the change in background broke the script. I try to make this feature proof as much as I can but this is 2nd time it gets broken. I'll think about it and come up with a way that won't break it in the future meanwhile you can use Bookmark Method.

**Comment by Beennuked** [comment]
Thanks for acknowledging the issue currently! As someone that uses the web version of this plugin daily, it has been my go-to I was a little sad when it went down. Hoping for a fix soon!

Thanks again!

**Comment by WiLuX-Source** [comment]
I'm currently working on a draggable menu so it wont be affected by those changes and the users can put wherever they want it.

**Comment by WiLuX-Source** [comment]
Okay finished it. I added some extra features while dealing with it.
Don't forget to read "How To Use" for new features.
Don't forget to give us a star for support!
