### ISSUE TITLE
Script Method not showing

### ISSUE THREAD

**Issue by Beennuked** [WiLuX-Source/Discord-Token-Login#14]
Hey there!

Sorry to open a new issue, I want to make sure its not user error. The script method updated in tampermonkey, but I cannot get it to appear where it normally would. I checked to see if there were serious changes made, but I believe I am still supposed to be looking here? Thanks for all your work on this! Took screenshots of the area I am looking for the box and my updated tampermonkey script.

![Capture](https://user-images.githubusercontent.com/97627526/169618193-8d9ab415-dc85-4bf4-9ebf-7bf8c72d1d01.PNG)
![Capture2](https://user-images.githubusercontent.com/97627526/169618201-049adc65-8d6b-4da2-af4a-c339d040ae1d.PNG)

**Comment by WiLuX-Source** [comment]
It works on my side. I think that might be because of URL which URL you use?
The Account List should appear as soon as you open the site.

**Comment by WiLuX-Source** [comment]
It should open top left side on the screen by default. Tho you can drag the window and leave it there, It will save the current position and always open there.

**Comment by Beennuked** [comment]
Hmm the URL I am using is https://discord.com/login and I even uninstalled and reinstalled the script. That was also the URL I used prior to it breaking. I can try another computer when I wake up and see if I can get it on that computer and report back. I am not getting anything on discord left side either on this page. Screenshot attached. 

![Capture](https://user-images.githubusercontent.com/97627526/169639578-fd7f582d-c0cc-455f-a96f-2e8bbd683e26.PNG)

**Comment by WiLuX-Source** [comment]
Ok I identified the issue rn. It doesn't work with Tampermonkey but works with ViolentMonkey.

**Comment by WiLuX-Source** [comment]
Okay found the part where the issue is. Pushing...

**Comment by WiLuX-Source** [comment]
Let me know if it works now. I will keep this issue open for a while.

**Comment by Beennuked** [comment]
That worked! Not sure if you care, but the version on the box does not match the version you pushed. Box shows 1.4.2 
![Capture](https://user-images.githubusercontent.com/97627526/169640149-85a09739-5020-4616-80fe-6c2d9a652de7.PNG)

**Comment by WiLuX-Source** [comment]
Oh silly me oh my god.

**Comment by WiLuX-Source** [comment]
Ok last change should clear everything. Feel free to open another issue when something like this happens.

Like I said before :
If you want to support us please don't forget to give us star at the top right. Thanks for using this project.
