### ISSUE TITLE
Change the problem

### ISSUE THREAD

**Issue by RealShit0731** [WiLuX-Source/Discord-Token-Login#17]
Using google browser to add extension plug-ins, the following error occurs.

![image](https://user-images.githubusercontent.com/34395444/193424024-13a0828c-2f57-448a-9b42-6e9d0c8bc6f0.png)

**Comment by WiLuX-Source** [comment]
Because you need to build it first not select the folder.

**Comment by WiLuX-Source** [comment]
If you don't want to build you can just unpack the crx from the latest release with 7-zip or winrar

**Comment by WiLuX-Source** [comment]
I hope you fixed your issue. I close this due to inactivity.

**Comment by RealShit0731** [comment]
Okay thx sir
