### ISSUE TITLE
Can

### ISSUE THREAD

**Issue by RealShit0731** [WiLuX-Source/Discord-Token-Login#19]
![image](https://user-images.githubusercontent.com/34395444/202976519-5498ea66-8244-4d80-9f7b-8aa2af9f90a0.png)

**Comment by RealShit0731** [comment]
can't download crx file

**Comment by WiLuX-Source** [comment]
Hello,

This is the 3rd time you open this issue. I already told you how to fix this. Could you let me know which part you didn't understand from previous one so I can elaborate it?

This project has an issue template so please use that next time you open an issue.

**Comment by RealShit0731** [comment]
I don't know how to compile the chrome plugin




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月21日(星期一) 晚上10:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WiLuX-Source/Discord-Token-Login] Can (Issue #19)





 
你好，
 
这是您第 3 次打开此问题。我已经告诉过你如何解决这个问题。您能否让我知道您对上一节的哪一部分不理解，以便我详细说明？
 
这个项目有一个问题模板，所以请在下次打开问题时使用它。
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您创作了该线程。消息 ID：<WiLuX-Source/Discord-Token-Login/issues/19/1322168412 @ github 。com&gt;

**Comment by WiLuX-Source** [comment]
I said if you don't know how to compile it you can download CRX file with another browser or another client like wget & curl(which comes with git)

and extract with WinRAR & 7Zip

**Comment by RealShit0731** [comment]
Okay, Let me try




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月21日(星期一) 晚上10:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WiLuX-Source/Discord-Token-Login] Can (Issue #19)






我说如果你不知道如何编译它，你可以用其他浏览器或其他客户端下载CRX文件，比如wget&amp;curl（git自带的）

并使用WinRAR和7Zip提取

—
直接回复此邮件，在GitHub上查看，或取消订阅.
您收到此消息是因为您创作了该线程。留言ID:<Wi ***@***.***与&gt;.

**Comment by RealShit0731** [comment]
can't download sir


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WiLuX-Source/Discord-Token-Login"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月21日(星期一) 晚上10:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WiLuX-Source/Discord-Token-Login] Can (Issue #19)





 
I said if you don't know how to compile it you can download CRX file with another browser or another client like wget &amp; curl(which comes with git)
 
and extract with WinRAR &amp; 7Zip

**Comment by WiLuX-Source** [comment]
What did you use to download?

**Comment by WiLuX-Source** [comment]
I updated the release for your issue you can download 7z one and extract it without any extra work. Don't open issue without following the guidelines of this project & use our discord or continue to the old issue instead.

If you like the work being done here please give a star. Have a good day.
