### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by n0ky4** [WiLuX-Source/Discord-Token-Login#4]
When I try to login, appears a 401 (Not authorized) status code in Network Menu (Inspect element), also I cant have the access of account.

![image](https://user-images.githubusercontent.com/19615514/106338810-84943a80-6273-11eb-9911-78c2e8148244.png)

**Comment by n0ky4** [comment]
My token was wrong, im dumb sorry

**Comment by WiLuX-Source** [comment]
It's Ok. Make Sure You Use Latest Version Of This Project I Added Tooltips For People Who Are New To The These Things.

Also If you like the project give us a star so we can reach other people as well :)
