### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by ghost** [WiLuX-Source/Discord-Token-Login#8]
I'm not sure if you're aware of this, but discord has stopped using local storage for storing tokens. Hence why I think this is no longer working. ( at least not for me ), In my case, it just returns me to the login page.

**Comment by WiLuX-Source** [comment]
Discord didn't stop using local storage for storing tokens.
Possible Reasons might be causing that:
- Wrong Token
- Bot Token

I tested the code again & it works.

**Comment by Desu403** [comment]
so you can "think" but you can't test if it's working or not Julie  lmao.

**Comment by WiLuX-Source** [comment]
ah yeah as de4su said don't include **'** or **"**
This is same for all of the methods.
